# Release package to PyPI upon tag push

name: Release

on:
  # Triggers the workflow on tag push
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest]
        python: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      - name: Publish lisbon unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          sed -ie "s/version =.*dev.*/version = \"${GITHUB_REF/refs\/tags\/v/}\"/g" Cargo.toml && 
          RUSTFLAGS='-C target-feature=+avx2,+fma' maturin publish --skip-existing -i python${{ matrix.python }} \
          -u __token__ -p ${{ secrets.MATURIN_PASSWORD }}
      - name: Publish lisbon windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $TAG = $GITHUB_REF -replace '/refs/tags/v',''
          ((Get-Content -path Cargo.toml -Raw) -replace 'version =.*dev.*',"version = `"$TAG`"") | Set-Content -Path Cargo.toml
          set RUSTFLAGS='-C target-feature=+avx2,+fma'
          write-output $GITHUB_REF
          write-output $TAG
          get-Content Cargo.toml
          maturin publish --skip-existing -i python${{ matrix.python }} -u __token__ -p ${{ secrets.MATURIN_PASSWORD }}
