# Release package to PyPI upon tag push

name: Release

on:
  # Triggers the workflow on tag push
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      - name: Publish lisbon
        run: |
          sed -ie "s/version =.*dev.*/version = \"${GITHUB_REF/refs\/tags\/v/}\"/g" Cargo.toml && 
          RUSTFLAGS='-C target-feature=+avx2,+fma' maturin publish -i python${{ matrix.python }} \
          -u __token__ -p ${{ secrets.MATURIN_PASSWORD }}
